require("dotenv").config();
const mongoose = require("mongoose");
const Product = require("../models/products");
const User = require("../models/users");

const seedProducts = async () => {
    try {
        await mongoose.connect(process.env.MONGO_URI);
        console.log("DB connected");

        await Product.deleteMany();
        console.log("Old products deleted");

        const sellers = await User.find({ role: "seller" });

        if (!sellers.length) {
            throw new Error("No sellers found, seed users first");
        }

        
        const products = [
            {
                "seller": "693ec5772cb61a484222fb1e",
                "name": "Dell XPS 15 Laptop",
                "nameAr": "لابتوب ديل إكس بي إس 15",
                "slug": "dell-xps-15-laptop",
                "description": "High-performance new laptop with powerful specs, ideal for professionals and creators.",
                "descriptionAr": "لابتوب جديد عالي الأداء بمواصفات قوية، مثالي للمحترفين والمبدعين.",
                "category": "Laptops",
                "subCategory": "Ultrabook",
                "brand": "Dell",
                "sku": "LAP-001",
                "condition": "New",
                "price": 45000,
                "discount": 5,
                "stockQuantity": 15,
                "lowStockThreshold": 5,
                "technicalSpecs": {
                    "CPU": "Intel Core i7-13700H",
                    "RAM": "16GB DDR5",
                    "GPU": "NVIDIA RTX 4050",
                    "Storage": "1TB SSD",
                    "ScreenSize": "15.6 inch OLED",
                    "OS": "Windows 11",
                    "Color": "Silver"
                },
                "dimensions": { "length": 34.5, "width": 23, "height": 1.8 },
                "weight": { "value": 1.9 },
                "warranty": { "type": "Manufacturer", "duration": "2 years" },
                "images": [
                    "https://images.unsplash.com/photo-1541807084-5c3b6ebd076c",
                    "https://images.pexels.com/photos/18105/pexels-photo.jpg",
                    "https://images.unsplash.com/photo-1588872657578-39ef8e1f5e19",
                    "https://images.pexels.com/photos/7974/pexels-photo.jpg",
                    "https://images.unsplash.com/photo-1525547719571-a2d4ac8945ff"
                ],
                "isFeatured": true,
                "visibility": "Published",
                "ratingsAverage": 4.8,
                "ratingsQuantity": 120
            },
            {
                "seller": "693ec5772cb61a484222fb1c",
                "name": "ASUS ROG Strix Gaming Laptop",
                "nameAr": "لابتوب أسوس روج ستريكس للألعاب",
                "slug": "asus-rog-strix-gaming-laptop",
                "description": "Powerful gaming laptop with RGB lighting and high refresh rate screen.",
                "descriptionAr": "لابتوب ألعاب قوي مع إضاءة RGB وشاشة عالية التحديث.",
                "category": "Laptops",
                "subCategory": "Gaming",
                "brand": "ASUS",
                "sku": "LAP-002",
                "condition": "New",
                "price": 65000,
                "discount": 10,
                "stockQuantity": 8,
                "lowStockThreshold": 5,
                "technicalSpecs": {
                    "CPU": "AMD Ryzen 9 7945HX",
                    "RAM": "32GB DDR5",
                    "GPU": "NVIDIA RTX 4080",
                    "Storage": "2TB SSD",
                    "ScreenSize": "17.3 inch 240Hz",
                    "OS": "Windows 11",
                    "Color": "Black"
                },
                "dimensions": { "length": 39.5, "width": 28.2, "height": 2.8 },
                "weight": { "value": 2.9 },
                "warranty": { "type": "Manufacturer", "duration": "1 year" },
                "images": [
                    "https://images.unsplash.com/photo-1603304068532-6e0c14d1e7fd",
                    "https://images.pexels.com/photos/17183938/pexels-photo-17183938.jpeg",
                    "https://images.unsplash.com/photo-1587614382346-4ec70e24210e",
                    "https://images.unsplash.com/photo-1590650516494-0c8e4a4dd67e",
                    "https://images.pexels.com/photos/1229861/pexels-photo-1229861.jpeg"
                ],
                "isFeatured": true,
                "visibility": "Published",
                "ratingsAverage": 4.7,
                "ratingsQuantity": 95
            },
            {
                "seller": "693ec5772cb61a484222fb1c",
                "name": "MacBook Pro 14 M3",
                "nameAr": "ماك بوك برو 14 إم3",
                "slug": "macbook-pro-14-m3",
                "description": "Premium Apple laptop with M3 chip for ultimate performance.",
                "descriptionAr": "لابتوب أبل بريميوم بشريحة إم3 لأداء فائق.",
                "category": "Laptops",
                "subCategory": "Professional",
                "brand": "Apple",
                "sku": "LAP-003",
                "condition": "Imported",
                "price": 85000,
                "discount": 0,
                "stockQuantity": 12,
                "lowStockThreshold": 5,
                "technicalSpecs": {
                    "CPU": "Apple M3 Pro",
                    "RAM": "18GB Unified",
                    "GPU": "Integrated 14-core",
                    "Storage": "512GB SSD",
                    "ScreenSize": "14.2 inch Liquid Retina XDR",
                    "OS": "macOS",
                    "Color": "Space Gray"
                },
                "dimensions": { "length": 31.3, "width": 22.1, "height": 1.55 },
                "weight": { "value": 1.6 },
                "warranty": { "type": "Agent", "duration": "1 year" },
                "images": [
                    "https://images.unsplash.com/photo-1517336714731-489689fd1ca8",
                    "https://images.pexels.com/photos/303383/pexels-photo-303383.jpeg",
                    "https://images.unsplash.com/photo-1544244011-2b3c569e7b0e",
                    "https://images.unsplash.com/photo-1531297484001-80022131f5a1",
                    "https://images.pexels.com/photos/434346/pexels-photo-434346.jpeg"
                ],
                "isFeatured": false,
                "visibility": "Published",
                "ratingsAverage": 4.9,
                "ratingsQuantity": 200,
                "importedDetails": {
                    "countryOfOrigin": "USA",
                    "importDate": "2025-11-01",
                    "internationalWarranty": true,
                    "compatibilityNotes": ""
                }
            },
            {
                "seller": "693ec5772cb61a484222fb1c",
                "name": "HP Pavilion Desktop",
                "nameAr": "ديسكتوب إتش بي بافيليون",
                "slug": "hp-pavilion-desktop",
                "description": "Reliable office desktop for everyday tasks.",
                "descriptionAr": "ديسكتوب مكتبي موثوق للمهام اليومية.",
                "category": "Desktops",
                "subCategory": "Office",
                "brand": "HP",
                "sku": "DESK-004",
                "condition": "New",
                "price": 25000,
                "discount": 8,
                "stockQuantity": 20,
                "lowStockThreshold": 5,
                "technicalSpecs": {
                    "CPU": "Intel Core i5-13400",
                    "RAM": "16GB",
                    "GPU": "Integrated",
                    "Storage": "1TB HDD + 256GB SSD",
                    "OS": "Windows 11",
                    "ScreenSize": "",
                    "Color": ""
                },
                "dimensions": { "length": 33.8, "width": 15.5, "height": 30.3 },
                "weight": { "value": 6.5 },
                "warranty": { "type": "Manufacturer", "duration": "3 years" },
                "images": [
                    "https://images.unsplash.com/photo-1587831990711-23ca6441447b",
                    "https://images.pexels.com/photos/38568/apple-imac-ipad-workplace-38568.jpeg",
                    "https://images.unsplash.com/photo-1559163535-5b1f3e8c3c0b",
                    "https://images.unsplash.com/photo-15977358890-4d92d3d2d8d8",
                    "https://images.pexels.com/photos/1591060/pexels-photo-1591060.jpeg"
                ],
                "isFeatured": false,
                "visibility": "Published",
                "ratingsAverage": 4.4,
                "ratingsQuantity": 60
            },
            {
                "seller": "693ec5772cb61a484222fb1e",
                "name": "Custom RGB Gaming Desktop",
                "nameAr": "ديسكتوب ألعاب مخصص RGB",
                "slug": "custom-rgb-gaming-desktop",
                "description": "High-end gaming PC with custom water cooling.",
                "descriptionAr": "كمبيوتر ألعاب عالي الجودة مع تبريد مائي مخصص.",
                "category": "Desktops",
                "subCategory": "Gaming",
                "brand": "Custom",
                "sku": "DESK-005",
                "condition": "New",
                "price": 95000,
                "discount": 15,
                "stockQuantity": 5,
                "lowStockThreshold": 5,
                "technicalSpecs": {
                    "CPU": "Intel Core i9-14900K",
                    "RAM": "64GB DDR5",
                    "GPU": "NVIDIA RTX 4090",
                    "Storage": "4TB SSD",
                    "OS": "No OS",
                    "ScreenSize": "",
                    "Color": ""
                },
                "dimensions": { "length": 50, "width": 23, "height": 50 },
                "weight": { "value": 15 },
                "warranty": { "type": "Seller", "duration": "2 years" },
                "images": [
                    "https://images.unsplash.com/photo-1587201572498-2f8e9e9e3b7d",
                    "https://images.pexels.com/photos/7771894/pexels-photo-7771894.jpeg",
                    "https://images.unsplash.com/photo-1614624532983-4ce03382d63d",
                    "https://images.unsplash.com/photo-1590399822207-665695e7e2d1",
                    "https://images.pexels.com/photos/8412282/pexels-photo-8412282.jpeg"
                ],
                "isFeatured": true,
                "visibility": "Published",
                "ratingsAverage": 4.9,
                "ratingsQuantity": 45
            },
            {
                "seller": "693ec5772cb61a484222fb1e",
                "name": "Lenovo ThinkCentre Mini PC",
                "nameAr": "ميني بي سي لينوفو ثينك سنتر",
                "slug": "lenovo-thinkcentre-mini-pc",
                "description": "Compact desktop for business use.",
                "descriptionAr": "ديسكتوب صغير الحجم للاستخدام التجاري.",
                "category": "Desktops",
                "subCategory": "Mini PC",
                "brand": "Lenovo",
                "sku": "DESK-006",
                "condition": "Used",
                "price": 15000,
                "discount": 20,
                "stockQuantity": 10,
                "lowStockThreshold": 5,
                "technicalSpecs": {
                    "CPU": "Intel Core i7-10700",
                    "RAM": "16GB",
                    "GPU": "Integrated",
                    "Storage": "512GB SSD",
                    "ScreenSize": "",
                    "OS": "",
                    "Color": ""
                },
                "dimensions": { "length": 18, "width": 18, "height": 3.5 },
                "weight": { "value": 1.3 },
                "warranty": { "type": "Seller", "duration": "6 months" },
                "images": [
                    "https://images.unsplash.com/photo-1551647637-9a6d9d9c9002",
                    "https://images.pexels.com/photos/1591060/pexels-photo-1591060.jpeg",
                    "https://images.unsplash.com/photo-1587831990711-23ca6441447b",
                    "https://images.pexels.com/photos/38568/apple-imac-ipad-workplace-38568.jpeg"
                ],
                "isFeatured": false,
                "visibility": "Published",
                "ratingsAverage": 4.2,
                "ratingsQuantity": 30,
                "usedDetails": {
                    "deviceConditionDescription": "Excellent condition, like new",
                    "previousUsageDuration": "1 year",
                    "manufacturingYear": 2023,
                    "refurbishmentNotes": "",
                    "signsOfWear": ""
                }
            },
            {
                "seller": "693ec5772cb61a484222fb1c",
                "name": "Logitech MX Master 3 Mouse",
                "nameAr": "ماوس لوجيتك إم إكس ماستر 3",
                "slug": "logitech-mx-master-3-mouse",
                "description": "Ergonomic wireless mouse for productivity.",
                "descriptionAr": "ماوس لاسلكي مريح للإنتاجية.",
                "category": "Accessories",
                "subCategory": "Mouse",
                "brand": "Logitech",
                "sku": "ACC-007",
                "condition": "New",
                "price": 4500,
                "discount": 0,
                "stockQuantity": 50,
                "lowStockThreshold": 5,
                "technicalSpecs": {
                    "CPU": "",
                    "RAM": "",
                    "GPU": "",
                    "Storage": "",
                    "ScreenSize": "",
                    "OS": "",
                    "Color": "Graphite"
                },
                "dimensions": { "length": 12.5, "width": 8.4, "height": 5.1 },
                "weight": { "value": 0.141 },
                "warranty": { "type": "Manufacturer", "duration": "2 years" },
                "images": [
                    "https://images.unsplash.com/photo-1615663249519-345f9b0f11c9",
                    "https://images.pexels.com/photos/1181271/pexels-photo-1181271.jpeg",
                    "https://images.unsplash.com/photo-1527814050087-37916d4da3f4",
                    "https://images.unsplash.com/photo-1586816879370-2c54add055a7",
                    "https://images.pexels.com/photos/374916/pexels-photo-374916.jpeg"
                ],
                "isFeatured": true,
                "visibility": "Published",
                "ratingsAverage": 4.8,
                "ratingsQuantity": 300
            },
            {
                "seller": "693ec5772cb61a484222fb1e",
                "name": "Razer DeathAdder V2 Gaming Mouse",
                "nameAr": "ماوس ألعاب ريزر ديث أدر V2",
                "slug": "razer-deathadder-v2-gaming-mouse",
                "description": "High-precision gaming mouse with RGB.",
                "descriptionAr": "ماوس ألعاب عالي الدقة مع RGB.",
                "category": "Accessories",
                "subCategory": "Mouse",
                "brand": "Razer",
                "sku": "ACC-008",
                "condition": "New",
                "price": 3500,
                "discount": 12,
                "stockQuantity": 35,
                "lowStockThreshold": 5,
                "technicalSpecs": {
                    "CPU": "",
                    "RAM": "",
                    "GPU": "",
                    "Storage": "",
                    "ScreenSize": "",
                    "OS": "",
                    "Color": "Black"
                },
                "dimensions": { "length": 12.7, "width": 7, "height": 4.3 },
                "weight": { "value": 0.082 },
                "warranty": { "type": "Manufacturer", "duration": "2 years" },
                "images": [
                    "https://images.unsplash.com/photo-1633359646094-72232d9c5c8e",
                    "https://images.pexels.com/photos/1181244/pexels-photo-1181244.jpeg",
                    "https://images.unsplash.com/photo-1615663249519-345f9b0f11c9",
                    "https://images.unsplash.com/photo-1586816879370-2c54add055a7"
                ],
                "isFeatured": false,
                "visibility": "Published",
                "ratingsAverage": 4.6,
                "ratingsQuantity": 180
            },
            {
                "seller": "693ec5772cb61a484222fb1e",
                "name": "Corsair K70 RGB Keyboard",
                "nameAr": "كيبورد كورسير K70 RGB",
                "slug": "corsair-k70-rgb-keyboard",
                "description": "Mechanical gaming keyboard with Cherry MX switches.",
                "descriptionAr": "كيبورد ألعاب ميكانيكي مع سويتشات شيري إم إكس.",
                "category": "Accessories",
                "subCategory": "Keyboard",
                "brand": "Corsair",
                "sku": "ACC-009",
                "condition": "New",
                "price": 6500,
                "discount": 10,
                "stockQuantity": 25,
                "lowStockThreshold": 5,
                "technicalSpecs": {
                    "CPU": "",
                    "RAM": "",
                    "GPU": "",
                    "Storage": "",
                    "ScreenSize": "",
                    "OS": "",
                    "Color": "Black"
                },
                "dimensions": { "length": 43.7, "width": 16.5, "height": 3.8 },
                "weight": { "value": 1.2 },
                "warranty": { "type": "Manufacturer", "duration": "2 years" },
                "images": [
                    "https://images.unsplash.com/photo-1600585154340-be6161a56a0c",
                    "https://images.pexels.com/photos/1181263/pexels-photo-1181263.jpeg",
                    "https://images.unsplash.com/photo-1624371402947-6ec3e2819a3e",
                    "https://images.unsplash.com/photo-1541140532154-0801b899c1e4",
                    "https://images.pexels.com/photos/1772123/pexels-photo-1772123.jpeg"
                ],
                "isFeatured": true,
                "visibility": "Published",
                "ratingsAverage": 4.7,
                "ratingsQuantity": 150
            },
            {
                "seller": "693ec5772cb61a484222fb1c",
                "name": "HyperX Cloud II Gaming Headset",
                "nameAr": "سماعة ألعاب هايبر إكس كلاود II",
                "slug": "hyperx-cloud-ii-gaming-headset",
                "description": "Comfortable gaming headset with 7.1 surround sound.",
                "descriptionAr": "سماعة ألعاب مريحة مع صوت محيطي 7.1.",
                "category": "Accessories",
                "subCategory": "Headset",
                "brand": "HyperX",
                "sku": "ACC-010",
                "condition": "Imported",
                "price": 4500,
                "discount": 5,
                "stockQuantity": 40,
                "lowStockThreshold": 5,
                "technicalSpecs": {
                    "CPU": "",
                    "RAM": "",
                    "GPU": "",
                    "Storage": "",
                    "ScreenSize": "",
                    "OS": "",
                    "Color": "Red"
                },
                "dimensions": { "length": 20, "width": 17, "height": 10 },
                "weight": { "value": 0.35 },
                "warranty": { "type": "Agent", "duration": "1 year" },
                "images": [
                    "https://images.unsplash.com/photo-1618843479313-40f8e8030789",
                    "https://images.pexels.com/photos/3945314/pexels-photo-3945314.jpeg",
                    "https://images.unsplash.com/photo-1583394838336-3e2f9e337393",
                    "https://images.unsplash.com/photo-1609093057717-3e2dd1c271e1"
                ],
                "isFeatured": false,
                "visibility": "Published",
                "ratingsAverage": 4.5,
                "ratingsQuantity": 220,
                "importedDetails": {
                    "countryOfOrigin": "China",
                    "importDate": "2025-10-15",
                    "internationalWarranty": false,
                    "compatibilityNotes": ""
                }
            },
            {
                "seller": "693ec5772cb61a484222fb1c",
                "name": "NVIDIA GeForce RTX 4090 GPU",
                "nameAr": "كرت شاشة إنفيديا RTX 4090",
                "slug": "nvidia-geforce-rtx-4090-gpu",
                "description": "Top-tier graphics card for gaming and AI.",
                "descriptionAr": "كرت شاشة من الطراز الأول للألعاب والذكاء الاصطناعي.",
                "category": "Components",
                "subCategory": "GPU",
                "brand": "NVIDIA",
                "sku": "COMP-011",
                "condition": "New",
                "price": 85000,
                "discount": 0,
                "stockQuantity": 7,
                "lowStockThreshold": 5,
                "technicalSpecs": {
                    "CPU": "",
                    "RAM": "",
                    "GPU": "GeForce RTX 4090",
                    "Storage": "",
                    "ScreenSize": "",
                    "OS": "",
                    "Color": ""
                },
                "dimensions": { "length": 33.6, "width": 14, "height": 6.1 },
                "weight": { "value": 1.8 },
                "warranty": { "type": "Manufacturer", "duration": "3 years" },
                "images": [
                    "https://images.unsplash.com/photo-1591485421821-3ac4a2c12e3b",
                    "https://images.unsplash.com/photo-1631093499980-3db997f22b47",
                    "https://images.unsplash.com/photo-1590139422482-577e85f738a8",
                    "https://images.unsplash.com/photo-1631093378863-7d144d1e23f5",
                    "https://images.pexels.com/photos/1181275/pexels-photo-1181275.jpeg"
                ],
                "isFeatured": true,
                "visibility": "Published",
                "ratingsAverage": 5.0,
                "ratingsQuantity": 80
            },
            {
                "seller": "693ec5772cb61a484222fb1c",
                "name": "Intel Core i9-14900K CPU",
                "nameAr": "معالج إنتل كور آي9-14900K",
                "slug": "intel-core-i9-14900k-cpu",
                "description": "Latest generation high-performance CPU.",
                "descriptionAr": "معالج الجيل الأحدث عالي الأداء.",
                "category": "Components",
                "subCategory": "CPU",
                "brand": "Intel",
                "sku": "COMP-012",
                "condition": "New",
                "price": 28000,
                "discount": 5,
                "stockQuantity": 12,
                "lowStockThreshold": 5,
                "technicalSpecs": {
                    "CPU": "Intel Core i9-14900K",
                    "RAM": "",
                    "GPU": "",
                    "Storage": "",
                    "ScreenSize": "",
                    "OS": "",
                    "Color": ""
                },
                "dimensions": { "length": 4.5, "width": 4.5, "height": 1 },
                "weight": { "value": 0.1 },
                "warranty": { "type": "Manufacturer", "duration": "3 years" },
                "images": [
                    "https://images.unsplash.com/photo-1553062407-98eeb96417d6",
                    "https://images.unsplash.com/photo-1590650516494-0c8e4a4dd67e",
                    "https://images.unsplash.com/photo-1517077307056-2d4a8d9e9d6c",
                    "https://images.unsplash.com/photo-1586023492125-27b2c045499d"
                ],
                "isFeatured": false,
                "visibility": "Published",
                "ratingsAverage": 4.8,
                "ratingsQuantity": 100
            },
            {
                "seller": "693ec5772cb61a484222fb1c",
                "name": "Corsair Vengeance 32GB RAM Kit",
                "nameAr": "رام كورسير فينجنس 32 جيجا كيت",
                "slug": "corsair-vengeance-32gb-ram-kit",
                "description": "DDR5 RAM kit for high-speed performance.",
                "descriptionAr": "كيت رام DDR5 لأداء عالي السرعة.",
                "category": "Components",
                "subCategory": "RAM",
                "brand": "Corsair",
                "sku": "COMP-013",
                "condition": "New",
                "price": 7500,
                "discount": 10,
                "stockQuantity": 30,
                "lowStockThreshold": 5,
                "technicalSpecs": {
                    "CPU": "",
                    "RAM": "32GB DDR5",
                    "GPU": "",
                    "Storage": "",
                    "ScreenSize": "",
                    "OS": "",
                    "Color": ""
                },
                "dimensions": { "length": 13.5, "width": 0.7, "height": 3.3 },
                "weight": { "value": 0.1 },
                "warranty": { "type": "Manufacturer", "duration": "Lifetime" },
                "images": [
                    "https://images.unsplash.com/photo-1591799255099-2a0d5f2e3c51",
                    "https://images.unsplash.com/photo-1631093378863-7d144d1e23f5",
                    "https://images.unsplash.com/photo-1586023492120-13c95f7dd4c3",
                    "https://images.unsplash.com/photo-1631093489355-2b4743e7b5d6"
                ],
                "isFeatured": false,
                "visibility": "Published",
                "ratingsAverage": 4.7,
                "ratingsQuantity": 140
            },
            {
                "seller": "693ec5772cb61a484222fb1c",
                "name": "Samsung 990 PRO 2TB SSD",
                "nameAr": "إس إس دي سامسونج 990 برو 2 تيرا",
                "slug": "samsung-990-pro-2tb-ssd",
                "description": "Ultra-fast NVMe SSD for storage.",
                "descriptionAr": "إس إس دي NVMe فائق السرعة للتخزين.",
                "category": "Components",
                "subCategory": "Storage",
                "brand": "Samsung",
                "sku": "COMP-014",
                "condition": "New",
                "price": 9500,
                "discount": 0,
                "stockQuantity": 18,
                "lowStockThreshold": 5,
                "technicalSpecs": {
                    "CPU": "",
                    "RAM": "",
                    "GPU": "",
                    "Storage": "2TB NVMe SSD",
                    "ScreenSize": "",
                    "OS": "",
                    "Color": ""
                },
                "dimensions": { "length": 8, "width": 2.2, "height": 0.2 },
                "weight": { "value": 0.009 },
                "warranty": { "type": "Manufacturer", "duration": "5 years" },
                "images": [
                    "https://images.unsplash.com/photo-1599499891420-4f1582d0cb9d",
                    "https://images.unsplash.com/photo-1631093489355-2b4743e7b5d6",
                    "https://images.unsplash.com/photo-1586023492125-27b2c045499d",
                    "https://images.unsplash.com/photo-1591799255099-2a0d5f2e3c51"
                ],
                "isFeatured": true,
                "visibility": "Published",
                "ratingsAverage": 4.9,
                "ratingsQuantity": 160
            },
            {
                "seller": "693ec5772cb61a484222fb1c",
                "name": "Dell UltraSharp 27 Monitor",
                "nameAr": "شاشة ديل ألترا شارب 27 إنش",
                "slug": "dell-ultrasharp-27-monitor",
                "description": "4K monitor for professional work.",
                "descriptionAr": "شاشة 4K للعمل الاحترافي.",
                "category": "Accessories",
                "subCategory": "Monitor",
                "brand": "Dell",
                "sku": "ACC-015",
                "condition": "New",
                "price": 22000,
                "discount": 8,
                "stockQuantity": 14,
                "lowStockThreshold": 5,
                "technicalSpecs": {
                    "CPU": "",
                    "RAM": "",
                    "GPU": "",
                    "Storage": "",
                    "ScreenSize": "27 inch 4K",
                    "OS": "",
                    "Color": ""
                },
                "dimensions": { "length": 61, "width": 18, "height": 40 },
                "weight": { "value": 6.5 },
                "warranty": { "type": "Manufacturer", "duration": "3 years" },
                "images": [
                    "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf",
                    "https://images.pexels.com/photos/3183150/pexels-photo-3183150.jpeg",
                    "https://images.unsplash.com/photo-1581291518633-83b4ebd88d88",
                    "https://images.unsplash.com/photo-1590650516494-0c8e4a4dd67e",
                    "https://images.pexels.com/photos/777001/pexels-photo-777001.jpeg"
                ],
                "isFeatured": false,
                "visibility": "Published",
                "ratingsAverage": 4.6,
                "ratingsQuantity": 90
            },
            {
                "seller": "693ec5772cb61a484222fb1e",
                "name": "ASUS TUF Gaming Laptop (Used)",
                "nameAr": "لابتوب أسوس توف ألعاب (مستعمل)",
                "slug": "asus-tuf-gaming-laptop-used",
                "description": "Used gaming laptop in excellent condition.",
                "descriptionAr": "لابتوب ألعاب مستعمل بحالة ممتازة.",
                "category": "Laptops",
                "subCategory": "Gaming",
                "brand": "ASUS",
                "sku": "LAP-016",
                "condition": "Used",
                "price": 35000,
                "discount": 15,
                "stockQuantity": 3,
                "lowStockThreshold": 5,
                "technicalSpecs": {
                    "CPU": "Intel Core i7-12700H",
                    "RAM": "16GB",
                    "GPU": "RTX 3060",
                    "Storage": "1TB SSD",
                    "ScreenSize": "15.6 inch 144Hz",
                    "OS": "",
                    "Color": ""
                },
                "dimensions": { "length": 35.9, "width": 25.6, "height": 2.5 },
                "weight": { "value": 2.2 },
                "warranty": { "type": "Seller", "duration": "6 months" },
                "images": [
                    "https://images.unsplash.com/photo-1600585154340-be6161a56a0c",
                    "https://images.pexels.com/photos/1229861/pexels-photo-1229861.jpeg",
                    "https://images.unsplash.com/photo-1590650516494-0c8e4a4dd67e",
                    "https://images.unsplash.com/photo-1588872657578-39ef8e1f5e19"
                ],
                "isFeatured": false,
                "visibility": "Published",
                "ratingsAverage": 4.3,
                "ratingsQuantity": 40,
                "usedDetails": {
                    "deviceConditionDescription": "Minor scratches on lid",
                    "previousUsageDuration": "1.5 years",
                    "manufacturingYear": 2023,
                    "refurbishmentNotes": "",
                    "signsOfWear": "Light keyboard wear"
                }
            },
            {
                "seller": "693ec5772cb61a484222fb1e",
                "name": "Alienware Desktop (Imported)",
                "nameAr": "ديسكتوب ألينوير (مستورد)",
                "slug": "alienware-desktop-imported",
                "description": "Imported high-end gaming desktop.",
                "descriptionAr": "ديسكتوب ألعاب عالي الجودة مستورد.",
                "category": "Desktops",
                "subCategory": "Gaming",
                "brand": "Alienware",
                "sku": "DESK-017",
                "condition": "Imported",
                "price": 120000,
                "discount": 0,
                "stockQuantity": 4,
                "lowStockThreshold": 5,
                "technicalSpecs": {
                    "CPU": "Intel Core i9",
                    "RAM": "32GB",
                    "GPU": "RTX 4080",
                    "Storage": "2TB SSD",
                    "ScreenSize": "",
                    "OS": "",
                    "Color": ""
                },
                "dimensions": { "length": 55, "width": 25, "height": 50 },
                "weight": { "value": 18 },
                "warranty": { "type": "Agent", "duration": "2 years" },
                "images": [
                    "https://images.unsplash.com/photo-1614624532983-4ce03382d63d",
                    "https://images.pexels.com/photos/8412282/pexels-photo-8412282.jpeg",
                    "https://images.unsplash.com/photo-1587201572498-2f8e9e9e3b7d",
                    "https://images.unsplash.com/photo-1590399822207-665695e7e2d1"
                ],
                "isFeatured": true,
                "visibility": "Published",
                "ratingsAverage": 4.8,
                "ratingsQuantity": 55,
                "importedDetails": {
                    "countryOfOrigin": "USA",
                    "importDate": "2025-09-20",
                    "internationalWarranty": true,
                    "compatibilityNotes": ""
                }
            },
            {
                "seller": "693ec5772cb61a484222fb1c",
                "name": "SteelSeries Rival 600 Mouse",
                "nameAr": "ماوس ستيل سيريز رايفال 600",
                "slug": "steelseries-rival-600-mouse",
                "description": "Dual sensor gaming mouse.",
                "descriptionAr": "ماوس ألعاب بمستشعر مزدوج.",
                "category": "Accessories",
                "subCategory": "Mouse",
                "brand": "SteelSeries",
                "sku": "ACC-018",
                "condition": "New",
                "price": 4000,
                "discount": 10,
                "stockQuantity": 28,
                "lowStockThreshold": 5,
                "technicalSpecs": {
                    "CPU": "",
                    "RAM": "",
                    "GPU": "",
                    "Storage": "",
                    "ScreenSize": "",
                    "OS": "",
                    "Color": ""
                },
                "dimensions": { "length": 0, "width": 0, "height": 0 },
                "weight": { "value": 0 },
                "warranty": { "type": "Manufacturer", "duration": "2 years" },
                "images": [
                    "https://images.unsplash.com/photo-1527814050087-37916d4da3f4",
                    "https://images.pexels.com/photos/1181271/pexels-photo-1181271.jpeg",
                    "https://images.unsplash.com/photo-1633359646094-72232d9c5c8e",
                    "https://images.unsplash.com/photo-1586816879370-2c54add055a7"
                ],
                "isFeatured": false,
                "visibility": "Published",
                "ratingsAverage": 4.5,
                "ratingsQuantity": 110
            },
            {
                "seller": "693ec5772cb61a484222fb1e",
                "name": "Kingston 1TB SSD",
                "nameAr": "إس إس دي كينجستون 1 تيرا",
                "slug": "kingston-1tb-ssd",
                "description": "Reliable SATA SSD for upgrades.",
                "descriptionAr": "إس إس دي SATA موثوق للترقية.",
                "category": "Components",
                "subCategory": "Storage",
                "brand": "Kingston",
                "sku": "COMP-019",
                "condition": "New",
                "price": 3500,
                "discount": 5,
                "stockQuantity": 45,
                "lowStockThreshold": 5,
                "technicalSpecs": {
                    "CPU": "",
                    "RAM": "",
                    "GPU": "",
                    "Storage": "1TB SATA SSD",
                    "ScreenSize": "",
                    "OS": "",
                    "Color": ""
                },
                "dimensions": { "length": 10, "width": 7, "height": 0.7 },
                "weight": { "value": 0.05 },
                "warranty": { "type": "Manufacturer", "duration": "3 years" },
                "images": [
                    "https://images.unsplash.com/photo-1599499891420-4f1582d0cb9d",
                    "https://images.unsplash.com/photo-1631093489355-2b4743e7b5d6",
                    "https://images.unsplash.com/photo-1586023492125-27b2c045499d"
                ],
                "isFeatured": false,
                "visibility": "Published",
                "ratingsAverage": 4.4,
                "ratingsQuantity": 200
            },
            {
                "seller": "693ec5772cb61a484222fb1e",
                "name": "AMD Ryzen 7 7800X3D CPU",
                "nameAr": "معالج إيه إم دي رايزن 7 7800X3D",
                "slug": "amd-ryzen-7-7800x3d-cpu",
                "description": "Best gaming CPU with 3D V-Cache.",
                "descriptionAr": "أفضل معالج ألعاب مع 3D V-Cache.",
                "category": "Components",
                "subCategory": "CPU",
                "brand": "AMD",
                "sku": "COMP-020",
                "condition": "New",
                "price": 22000,
                "discount": 0,
                "stockQuantity": 10,
                "lowStockThreshold": 5,
                "technicalSpecs": {
                    "CPU": "AMD Ryzen 7 7800X3D",
                    "RAM": "",
                    "GPU": "",
                    "Storage": "",
                    "ScreenSize": "",
                    "OS": "",
                    "Color": ""
                },
                "dimensions": { "length": 4, "width": 4, "height": 0.8 },
                "weight": { "value": 0.08 },
                "warranty": { "type": "Manufacturer", "duration": "3 years" },
                "images": [
                    "https://images.unsplash.com/photo-1553062407-98eeb96417d6",
                    "https://images.unsplash.com/photo-1517077307056-2d4a8d9e9d6c",
                    "https://images.unsplash.com/photo-1590650516494-0c8e4a4dd67e",
                    "https://images.unsplash.com/photo-1586023492125-27b2c045499d",
                    "https://images.unsplash.com/photo-1631093378863-7d144d1e23f5"
                ],
                "isFeatured": true,
                "visibility": "Published",
                "ratingsAverage": 4.9,
                "ratingsQuantity": 130
            }
        ];

        await Product.insertMany(products);
        console.log("Products seeded successfully");

        process.exit();
    } catch (error) {
        console.error("Seeder error:", error);
        process.exit(1);
    }
};

seedProducts();
