const mongoose = require('mongoose');
const { Schema } = mongoose;

const OrderSchema = new Schema({
    // 1. Order Number: unique & generated by pre-save hook
    orderNumber: { 
        type: String, 
        unique: true, 
        sparse: true // 🚀 التصحيح 1: يسمح بوجود قيمة null في مستند واحد فقط
    },

    user: { type: Schema.Types.ObjectId, ref: 'User', required: true },

    items: [
        {
            product: { type: Schema.Types.ObjectId, ref: 'Product', required: true },
            name: { type: String, required: true }, 
            quantity: { type: Number, required: true, min: 1 },
            price: { type: Number, required: true }, // السعر الذي تم جلبه من السيرفر
            // 🚀 التصحيح 2: جعل 'condition' غير مطلوب (ليس required) لتجنب أخطاء التحقق
            condition: { type: String, enum: ['New', 'Used', 'Imported'] } 
        }
    ],

    // 2. 🚀 التصحيح 3: إضافة الحقول المالية المحسوبة لـ Schema
    totalAmount: { type: Number, required: true },
    VAT: { type: Number, default: 0 },
    deliveryFee: { type: Number, default: 0 },
    discount: { type: Number, default: 0 },

    paymentMethod: { type: String, enum: ['COD', 'Online'], required: true },
    paymentStatus: { type: String, enum: ['Pending', 'Paid', 'Refunded'], default: 'Pending' },

    // Shipping Address
    shippingAddress: {
        address: String,
        city: String,
        postalCode: String,
        country: String,
        phone: String
    },

    // Order Status Stages (كما هي)
    orderStatus: { 
        type: String, 
        enum: [
            'Order Placed', 'Payment Confirmed', 'Shipped', 
            'Out for Delivery', 'Delivered', 'Cancelled', 'Returned'
        ], 
        default: 'Order Placed' 
    },

    // Tracking & Dates (كما هي)
    estimatedDeliveryDate: Date,
    actualDeliveryDate: Date,
    trackingNumber: String,

    // Cancellation Logic (كما هي)
    isCancelled: { type: Boolean, default: false },
    cancellationReason: { 
        type: String, 
        enum: ['Changed my mind', 'Found better price', 'Ordered by mistake', 'Shipping takes too long', 'Other'] 
    },
    cancellationDate: Date,

    // Return Logic (كما هي)
    isReturnRequested: { type: Boolean, default: false },
    returnDetails: {
        reason: { 
            type: String, 
            enum: ['Product defective/damaged', 'Wrong item received', 'Product doesn\'t match description', 'Missing accessories/parts'] 
        },
        comment: String,
        proofImages: [String], 
        requestDate: Date,
        status: {
            type: String,
            enum: ['None', 'Return Requested', 'Return Approved', 'Return Rejected', 'Item Picked Up', 'Item Received', 'Quality Check', 'Refund Processed'],
            default: 'None'
        }
    }

}, { timestamps: true });

// Auto-generate Order Number (يجب استخدام هذه الدالة لتوليد القيمة الفريدة)



module.exports = mongoose.model('Order', OrderSchema);